kind: Service
apiVersion: v1
metadata:
  name: crux-bench-service
  labels:
    app: crux-bench-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: crux-bench
