apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datomic-transactor
  labels:
    app: datomic-transactor
spec:
  replicas: 1
  serviceName: datomic-transactor-service
  selector:
    matchLabels:
      app: datomic-transactor
  template:
    metadata:
      labels:
        app: datomic-transactor
        date: "1549290115"
    spec:
      containers:
      - name: datomic-transactor-free
        image: juxt/datomic-transactor-free:latest
        ports:
        - containerPort: 4334
        volumeMounts:
        - mountPath: "/var/datomic"
          name: app-data-5
        resources:
          limits:
            cpu: 1
            memory: 4Gi
  volumeClaimTemplates:
    - metadata:
        name: app-data-5
        annotations:
          volume.beta.kubernetes.io/storage-class: eu-west-1a-storage

      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
