version: '3.7'

services:
  website:
    build:
      context: .
      dockerfile: docker-files/Dockerfile.base

    restart: always
    command: lein repl :headless :host 0.0.0.0 :port 7889
    ports:
      - "7889:7889"
      - "8081:8080"

    environment:
      - AWS_PROFILE=crux
      - AWS_REGION=eu-west-1

      - CRUX_BENCHMARK_BUCKET=crux-bench-results

    working_dir: /app
    volumes:
      # Cache maven dependencies
      - "${HOME}/.m2:/root/.m2"
      # mount local leiningen profiles
      - "${HOME}/.lein:/root/.lein"
      # AWS credentials to upload s3 object
      - "${HOME}/.aws:/root/.aws"
      # Mount the application source and target directories
      - ./:/app

  datomic:
    build:
      context: .
      dockerfile: docker-files/datomic_transactor
    ports:
      - "4334:4334"
    volumes:
      # Cache maven dependencies
      - "./datomic/transactor.properties:/etc/datomic/transactor.properties"
      - "./datomic-data:/var/datomic"
      - "./logs:/var/log"
      - "${HOME}/.m2:/root/.m2"
